apiVersion: v1
kind: Service
metadata:
  name: my-webhook
  namespace: default
spec:
  selector:
    app: my-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
  type: ClusterIP